apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a8axl82jy-python
  janus-idp.io/tekton: a8axl82jy-python
  backstage.io/kubernetes-id: a8axl82jy-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: a8axl82jy-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
